language: c
sudo: required
before_install:
  - export PATH="/tmp/bin:$HOME/bin:$HOME/texlive/bin/x86_64-linux:$PATH"
install:
  - mkdir -p /tmp/bin && cd /tmp/bin
  - wget https://github.com/whudoc/statics/raw/master/qrsync.tar.gz
  - tar xfz qrsync.tar.gz
  - chmod +x qrsync
script:
  - cd ~/build/district10/texlive-pack;
  - chmod +x ./prepare.sh && ./prepare.sh packed-texlive.tar.xz
  - ls; ls publish
  - mkdir publish && cp packed*.tar.xz publish
  - cat conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > conf.json
  - make qiniu
